/* MōdSynth — Max for Live device logic.
   Generated by tools/build-m4l.js; rebuild rather than editing by hand.

   Three jobs:
     · turn a patch from patches.json into flat "<param> <value>" messages
     · fold the eight macros into the voice's off_* offsets, because gen~ has
       no dynamic routing and the matrix has to be resolved outside the DSP
     · turn Live's tempo into a delay time in seconds

   Outlet 0 → the voice parameter bus.  Outlet 1 → the effects parameter bus. */
autowatch = 1;
outlets = 2;
inlets = 1;

var VOICE = 0, FX = 1;
var bank = null;
var current = null;
var macroVals = [0, 0, 0, 0, 0, 0, 0, 0];
var modwheel = 0;
var tempo = 120;
var delayDiv = 0.125;          // in whole notes; 1 = one bar of 4/4

var DIV_BEATS = {"8n_1":32,"4n_1":16,"2n_1":8,"1_1":4,"1_2d":3,"1_2":2,"1_2t":1.3333333333333333,"1_4d":1.5,"1_4":1,"1_4t":0.6666666666666666,"1_8d":0.75,"1_8":0.5,"1_8t":0.3333333333333333,"1_16d":0.375,"1_16":0.25,"1_16t":0.16666666666666666,"1_32":0.125,"1_32t":0.08333333333333333,"1_64":0.0625};
var DIV_IDS = ["8n_1","4n_1","2n_1","1_1","1_2d","1_2","1_2t","1_4d","1_4","1_4t","1_8d","1_8","1_8t","1_16d","1_16","1_16t","1_32","1_32t","1_64"];

function dictionary(name) {
  // The [dict] object hands us its name; read the bank out of it once.
  var d = new Dict(name);
  try {
    bank = JSON.parse(d.stringify());
  } catch (e) {
    post("MōdSynth: could not read the patch bank — " + e.message + "\n");
  }
}

function patch(indexOrName) {
  if (!bank) { post("MōdSynth: no patch bank loaded yet.\n"); return; }
  var names = [];
  for (var k in bank) names.push(k);
  names.sort();
  var p = typeof indexOrName === "number" ? bank[names[indexOrName]] : bank[indexOrName];
  if (!p) { post("MōdSynth: no such patch: " + indexOrName + "\n"); return; }
  current = p;
  applyPatch(p);
}

function applyPatch(p) {
  for (var k in p.params) send(k, p.params[k]);
  for (var m in p.mods) send(m, p.mods[m]);
  // Anything the patch doesn't set has to be returned to zero, or the last
  // patch's modulation leaks into this one.
  var allMods = ["mod_lfo1_pitch","mod_lfo1_cutoff","mod_lfo1_pw","mod_lfo1_amp","mod_lfo1_shape","mod_lfo2_pitch","mod_lfo2_cutoff","mod_lfo2_shape","mod_lfo2_pan","mod_env2_pitch","mod_env2_shape","mod_env2_fm","mod_mw_lfo1depth","mod_mw_cutoff","mod_at_cutoff","mod_at_lfo1depth"];
  for (var i = 0; i < allMods.length; i++) {
    if (!(allMods[i] in p.mods)) send(allMods[i], 0);
  }
  resolveMacros();
}

/** Sums every macro's contribution into the voice's off_* offsets. */
function resolveMacros() {
  var off = { off_cutoff: 0, off_res: 0, off_detune: 0, off_shape: 0,
              off_pw: 0, off_fm: 0, off_pitch: 0, off_amp: 0 };
  if (current && current.macros) {
    for (var i = 0; i < current.macros.length; i++) {
      var r = current.macros[i];
      var v = r.macro === 0 ? modwheel : macroVals[r.macro - 1];
      if (r.offset in off) off[r.offset] += v * r.amt;
    }
  }
  for (var k in off) send(k, off[k]);
}

function send(name, value) {
  var target = (name.indexOf("fx_") === 0 || name.indexOf("master_") === 0) ? FX : VOICE;
  outlet(target, name, value);
}

/* live.* objects prepend their own name, so anything that isn't a known
   command arrives here as "<name> <value>". */
function anything() {
  var name = messagename;
  var v = arguments.length ? arguments[0] : 0;
  if (name.indexOf("macro_") === 0) {
    var idx = parseInt(name.substring(6), 10) - 1;
    if (idx >= 0 && idx < 8) { macroVals[idx] = v; resolveMacros(); }
    return;
  }
  if (name === "modwheel") { modwheel = v; resolveMacros(); }
  if (name === "fx_delay_div") { delayDiv = DIV_BEATS[DIV_IDS[Math.round(v)]] / 4 || 0.125; updateDelay(); return; }
  send(name, v);
}

function msg_float(v) {
  // The only bare float is the tempo from [snapshot~].
  tempo = v > 0 ? v : 120;
  updateDelay();
}

function updateDelay() {
  var beats = delayDiv * 4;
  var seconds = beats * 60 / tempo;
  if (seconds < 0.005) seconds = 0.005;
  if (seconds > 4) seconds = 4;
  outlet(FX, "fx_delay_time", seconds);
}
